# Numpy

In [1]:
import numpy as np

## 1. ndarry

In [2]:
np.array(1)

array(1)

In [3]:
type(np.array(1))

numpy.ndarray

In [4]:
np.array([1,2])

array([1, 2])

In [5]:
arr = np.arange(1000)

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr.ndim

2

In [10]:
arr.size

6

In [11]:
arr.shape

(2, 3)

In [13]:
arr.dtype

dtype('int64')

In [14]:
arr = np.array([1,2,3], dtype = np.float64)

In [15]:
arr.dtype

dtype('float64')

In [16]:
arr.astype(np.int32)

array([1, 2, 3], dtype=int32)

## 2. Arithmetic

### 2.1 Vectorization

In [17]:
arr = np.array([[1., 2., 3.],
                [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [19]:
arr * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [20]:
arr == arr

array([[ True,  True,  True],
       [ True,  True,  True]])

### 2.2 Transposing and swapping

In [21]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [23]:
np.dot(arr, arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [24]:
arr = np.arange(24).reshape((2,3,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
arr.T.shape

(4, 3, 2)

In [26]:
arr.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [27]:
arr.transpose(0,1,2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [29]:
arr.swapaxes(1,2)

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

### 2.3 Sizing, stacking, flatten, ravel

In [30]:
np.resize([1,2,3,4,5,6], (2,1))

array([[1],
       [2]])

In [31]:
np.resize([1,2], (3,2))

array([[1, 2],
       [1, 2],
       [1, 2]])

In [33]:
np.hstack(([1,2,3],[4,5,6]))

array([1, 2, 3, 4, 5, 6])

In [34]:
np.vstack(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
np.array([[1,2],[3,4]]).flatten()

array([1, 2, 3, 4])

In [36]:
np.array([[1,2],[3,4]]).ravel()

array([1, 2, 3, 4])

## 3. Indexing and slicing

In [37]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

5

In [40]:
arr[5:8]

array([5, 6, 7])

In [41]:
arr[5:8].copy()

array([5, 6, 7])

In [42]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.ndim

2

In [44]:
arr.shape

(3, 3)

In [45]:
arr[0]

array([1, 2, 3])

In [46]:
arr[0][2]

3

In [47]:
arr[0,2]

3

In [49]:
arr = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr.ndim

3

In [51]:
arr.shape

(2, 2, 3)

In [52]:
arr[0][0][1]

2

In [53]:
arr[0,0,1]

2

### 3.1 Boolean indexing

In [54]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
arr[arr > 4]

array([5, 6, 7, 8])

In [56]:
arr != 4

array([ True,  True,  True, False,  True,  True,  True,  True])

In [57]:
arr[(arr > 4) & (arr < 8)]

array([5, 6, 7])

In [58]:
np.where(arr > 4)

(array([4, 5, 6, 7]),)

### 3.2 Fancy indexing

In [59]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
# Rows
arr[[4,3,0,6],:]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [24, 25, 26, 27]])

In [61]:
# Columns
arr[:,[2,0]]

array([[ 2,  0],
       [ 6,  4],
       [10,  8],
       [14, 12],
       [18, 16],
       [22, 20],
       [26, 24],
       [30, 28]])

In [62]:
arr[[4,3,0,6],[0,3,2,1]]

array([16, 15,  2, 25])

## 4. Universal functions

In [63]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [66]:
np.sqrt(arr) * np.sqrt(arr)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
list(map(np.sqrt, arr))

[0.0,
 1.0,
 1.4142135623730951,
 1.7320508075688772,
 2.0,
 2.23606797749979,
 2.449489742783178,
 2.6457513110645907,
 2.8284271247461903,
 3.0]

In [69]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,5,4,3,2])

In [70]:
np.maximum(arr1, arr2)

array([6, 5, 4, 4, 5])

In [71]:
np.argmax(arr1)

4

## 5. Array-oriented programming

### 5.1 Conditional logic

In [72]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [73]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [74]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

### 5.2 Statistics

In [75]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr.mean()

4.5

In [78]:
arr.sum()

45

In [81]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [82]:
arr.mean(axis = 0)

array([ 8.,  9., 10., 11.])

In [83]:
arr.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [84]:
arr.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190])

### 5.3 Booleans

In [85]:
arr = np.random.randn(100)

In [86]:
(arr > 0).sum()

49

In [87]:
np.array([False, False, True, False]).any()

True

In [88]:
np.array([False, False, True, False]).all()

False

### 5.4 Sorting

In [89]:
arr = np.random.randn(6)
arr

array([ 1.21551899,  0.30108347,  0.74541635, -0.6309093 ,  0.20987023,
       -1.19221915])

In [90]:
arr.sort()
arr

array([-1.19221915, -0.6309093 ,  0.20987023,  0.30108347,  0.74541635,
        1.21551899])

In [91]:
np.sort(arr)

array([-1.19221915, -0.6309093 ,  0.20987023,  0.30108347,  0.74541635,
        1.21551899])

In [92]:
arr = np.random.randn(5,3)
arr

array([[ 0.73439045,  0.19462003,  1.13430352],
       [-0.13675475, -0.18472895, -1.07512495],
       [ 0.49524469,  0.53455823, -0.61072185],
       [ 1.85663929, -2.91279945, -0.01513263],
       [ 1.06644883,  1.04795072, -1.42317751]])

In [93]:
arr.sort(axis = 1)
arr

array([[ 0.19462003,  0.73439045,  1.13430352],
       [-1.07512495, -0.18472895, -0.13675475],
       [-0.61072185,  0.49524469,  0.53455823],
       [-2.91279945, -0.01513263,  1.85663929],
       [-1.42317751,  1.04795072,  1.06644883]])

In [94]:
arr.sort(axis = 0)
arr

array([[-2.91279945, -0.18472895, -0.13675475],
       [-1.42317751, -0.01513263,  0.53455823],
       [-1.07512495,  0.49524469,  1.06644883],
       [-0.61072185,  0.73439045,  1.13430352],
       [ 0.19462003,  1.04795072,  1.85663929]])

### 5.5 Set logic

In [95]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [96]:
values = np.array([6,0,0,3,2,5,6])
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

### 5.6 Broadcasting

In [97]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

## 6. File input and output

In [100]:
arr = np.arange(10)
np.save('some_array', arr)

In [101]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 7. Linear algebra

In [102]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6., 23.],[-1, 7],[8,9]])

In [103]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [104]:
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

## 8. Randomness

In [105]:
np.random.seed(1)

In [106]:
np.random.RandomState(1)

RandomState(MT19937) at 0x7FA4476F6E40